# Template with all config options and default values to be used as reference.
# Options in this file get overwritten by command line options.
# Required options can be passed through command line options instead
# Options with empty strings or left blank will be ignored.
gameid:                # Required if game-path is not used
game-path:             # Default: Automatic, or required if gameid is not used
demo-path:             # Required
raw-path:              # Default: Your OS's temp folder
steam-path:            # Default: Automatic
output-file:           # Default: 'summary_%Y-%m-%d_%H-%M-%S'
launch-options:        # Use double quotes for multiple launch options
presentmon-path: presentmon
passes: 5
loops: 1
discard-passes: 1
keep-first-pass: True
start-tick: 187
start-buffer: 2
duration: 20.0
tickrate: 66.6
no-baseline: False
verbosity: "WARNING"
comment: ""
tests:
  - name:              # Default: Concatenation of all changes, or ´baseline´ if there are no changes
    game-path:         # Will overwrite the game-path specified in the global options
    changes:
      cvars:
        -
      launch-options:
        -
